apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt-production
spec:
    acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: devin@devinsit.com
        privateKeySecretRef:
            name: letsencrypt-production
        solvers:
        - dns01:
            cloudDNS:
                serviceAccountSecretRef:
                    name: clouddns-service-account
                    key: service-account.json
                project: ufincs2
          selector: {}  # Match all domains
