---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ufincs
  namespace: cert-manager
spec:
  dnsNames:
  - ufincs.com
  - '*.ufincs.com'
  - '*.app.ufincs.com'
  - '*.backend.ufincs.com'
  - '*.marketing.ufincs.com'
  - '*.redesign.ufincs.com'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: ufincs-tls
